datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - ./objects/**
plugins:
  - "@steedos/accounts"
  - "@steedos/app-contracts"
  - "/Users/yinlianghui/Documents/GitHub/steedos-plugin-stimulsoft-report"